import type { Metadata } from "next";
import "./globals.css";
import "../styles/index";
import { natoSansKR } from "@/fonts/fonts";
import { cn } from "@/lib/utils";
import Providers from "@/lib/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
  ...props
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          natoSansKR.className,
          "h-screen overflow-hidden bg-background font-sans antialiased",
        )}
      >
        <Providers>
          {children}
          {modal}
          <div id="modal-root" />
          <div id="drawer-root" />
        </Providers>
      </body>
    </html>
  );
}
